# Generated by Django 4.2.5 on 2023-11-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_catalog_description_catalog_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='photo',
            field=models.ImageField(default=None, upload_to='photo/=', verbose_name='Картинка товара'),
        ),
    ]
