# Generated by Django 4.2.5 on 2023-11-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_name_alter_catalog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='photo',
            field=models.ImageField(default=None, upload_to='photo/%y/%m/%d', verbose_name='Картинка товара'),
        ),
    ]
