# Generated by Django 4.2.5 on 2023-11-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
